### PR TITLE
Fix for Issue #12

### PR DESCRIPTION
**Pull request by KundKMC**
Upload is working again #12

### CODE REVIEW

**Comment by MiniGlome** [comment]
I will check this out on Monday, 28 Aug

**Comment by Wolfvaudou** [comment]
The upload is working but, i think its related so i post it here, you cant share/ view the video if its not your account. I uploaded 2 video with it, i see it in my account and can read them if im connected with my account but the link used to share the video led to a unfound video on tiktok.

**Comment by MiniGlome** [comment]
It seems that TikTok changed a lot of things in its API since the bot was created and now detects that these sequence of requests does not come from the frontend.
I guess the script needs to be completely reworked but I have no time to do this. Feel free to use it for your own projects, but I'm going to stop maintaining it as I don't use it personally anymore.

**Comment by zegeree** [comment]
what system are you using right now? im willing to donate some money if you help me out

**Comment by zegeree** [comment]
> It seems that TikTok changed a lot of things in its API since the bot was created and now detects that these sequence of requests does not come from the frontend. I guess the script needs to be completely reworked but I have no time to do this. Feel free to use it for your own projects, but I'm going to stop maintaining it as I don't use it personally anymore.

im willing to pay you if you can fix it, or fix the https://github.com/wkaisertexas/tiktok-uploader script for me

**Pull request merged**
